[project]
name = "wechat-post"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "flake8>=7.1.2",
  "lxml[html-clean]>=5.3.1",
  "newspaper3k>=0.2.8",
  "requests>=2.32.3",
]
