[project]
name = "wechat-post"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flake8>=7.1.2",
    "requests>=2.32.3",
]
