name: WeChat Publish

on:
  workflow_dispatch:

  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: "Setup up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"
      - name: Install Ruff
        uses: astral-sh/ruff-action@v3
        with:
          version: "latest"
      - name: Ruff check
        run: ruff check --fix
      - name: Ruff format
        run: ruff format
      - name: Pushlish
        run: uv run main.py
